// DO NOT EDIT
  // this file is generated by /assets/configGen script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/corner-right-up'
  import IconBase from './../../IconBase'

  function IconCornerRightUp(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconCornerRightUp
  